agents/urls.py
from django.urls import path
from .views import *

app_name = 'agents'

urlpatterns = [
    path('', AgentsListView.as_view(), name='agent-lists'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='agent-delete'),
    path('agent-create/', AgentCreateView.as_view(), name='agent-create'),
]

back_medical/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import(
     LoginView,
     LogoutView,
     PasswordResetView,
     PasswordResetDoneView,
     PasswordResetConfirmView,
     PasswordResetCompleteView,
)
from records_feed.views import HomeView, RegisterView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('signup/', RegisterView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-reset-view/', PasswordResetView.as_view(), name='password_reset_view'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('', include('records_feed.urls')),
    path('agents/', include('agents.urls', namespace='agents'))
]

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from dataclasses import fields
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from records_feed.models import Agent

User = get_user_model()

class AgentCreateModel(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name'
        )

agents/views.py
import random
from django.views import generic
from django.core.mail import send_mail
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
# .mixins is actually for agents to show things and hiding
from .mixins import OraniserAndLoginRequiredMixin
from records_feed.models import Agent
from .forms import AgentCreateModel

class AgentsListView(OraniserAndLoginRequiredMixin, generic.ListView):
    template_name = 'agents/lists.html'
    context_object_name = 'agent'
    
    def get_queryset(self):
        organiser = self.request.user.userprofile
        return Agent.objects.filter(organiser=organiser)
    
class AgentCreateView(OraniserAndLoginRequiredMixin, generic.CreateView):
    template_name = 'agents/create.html'
    form_class = AgentCreateModel
    
    def get_success_url(self):
        return reverse('agents:agent-lists')
    
    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_organiser = False
        user.is_agent = True
        user.set_password(f"{random.randint(0, 10000)}")
        user.save()
        Agent.objects.create(
            user=user,
            organiser=self.request.user.userprofile
        )
        send_mail(
            subject='This user has been created',
            message='Created New User',
            from_email='husan3445@gmail.com',
            recipient_list=[user.email]
        )
        # agent.organiser = self.request.user.userprofile
        return super(AgentCreateView, self).form_valid(form)
    
class AgentDetailView(OraniserAndLoginRequiredMixin, generic.DetailView):
    template_name = 'agents/details.html'
    context_object_name = 'agent'
    
    def get_queryset(self):
        organiser = self.request.user.userprofile
        return Agent.objects.filter(organiser=organiser)
    
class AgentUpdateView(OraniserAndLoginRequiredMixin, generic.UpdateView):
    template_name = 'agents/update.html'
    form_class = AgentCreateModel
    context_object_name = 'agent'
    
    def get_success_url(self):
        return reverse('agents:agent-lists')
    
    def get_queryset(self):
        organiser = self.request.user.userprofile
        return Agent.objects.filter(organiser=organiser)
    
class AgentDeleteView(OraniserAndLoginRequiredMixin, generic.DeleteView):
    template_name = 'agents/delete.html'
    context_object_name = 'agent'
    
    def get_success_url(self):
        return reverse('agents:agent-lists')
    
    def get_queryset(self):
        organiser = self.request.user.userprofile
        return Agent.objects.filter(organiser=organiser)
    

agents/templates/agents/create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<link
  href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
  rel="stylesheet"
  id="bootstrap-css"
/>
<link rel="stylesheet" href="{% static 'css/forms.css' %}" />
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<section class="get-in-touch">
  <h1 class="title">Create Agents</h1>
  <form method="post">
    {% csrf_token %}
    {{ form | crispy }}
    <button type="submit" class="btn btn-primary w-100">Submit</button>
  </form>
</section>
{% endblock content %}

agents/templates/agents/delete.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<link
  href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
  rel="stylesheet"
  id="bootstrap-css"
/>
<link rel="stylesheet" href="{% static 'css/forms.css' %}" />
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<section class="get-in-touch">
  <h1 class="title">Are you sure to delete account?</h1>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary w-100">Submit</button>
  </form>
</section>
{% endblock content %}

agents/templates/agents/details.html
{% extends 'base.html' %}
{% block content %}
      <h1>{{ agent.user.username }}</h1>
      <a href="{% url 'agents:agent-update' agent.pk %}" class="btn btn-primary">update</a>
      <a href="{% url 'agents:agent-delete' agent.pk %}" class="btn btn-primary">delete</a>
{% endblock content %}

agents/templates/agents/lists.html
{% extends 'base.html' %}
{% block content %}
  <style>
    .feedback a {
      width: 100%;
      background-color: rgba(59, 56, 56, 0.5);
      padding: 20px 20px;
      text-decoration: none;
      font-size: 21px;
      display: block;
      margin-top: 5px;
      font-family: sans-serif;
      color: #444;
    }
  </style>
    <div class="feedback">
      <h2 style="font-family: sans-serif">National feedback users</h2>
      {% for agent in object_list %}
      <a href="{% url 'agents:agent-detail' agent.pk %}"
        >{{ agent.user.username }}</a
      >
      {% endfor %}
    </div>
{% endblock content %}

agents/templates/agents/update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/create.css' %}" />
<link
  rel="stylesheet"
  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
/>
<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js"
/>
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"
/>
<style>
</style>
<div class="container mt-5">
  <h2>Update</h2>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary w-100">Submit</button>
  </form>
</div>
{% endblock content %}